### PR TITLE
Create webui_train.py

### PR DESCRIPTION
**Pull request by kexul**
Add a webui for finetuning and inference from the finetuned model.
图片
图片

### CODE REVIEW

**Comment by aluminumbox** [comment]
please inform me to add you in dingding group, my name is 铝箱

**Comment by kexul** [comment]
> please inform me to add you in dingding group, my name is 铝箱

Sorry, I'm not affiliated with Alibaba. I just registered a new account in DingDing, but I can't find you with the user name you provided.

**Comment by cpken** [comment]
运行训练后报错了
```
Traceback (most recent call last):
  File "cosyvoice/bin/train.py", line 33, in <module>
    from cosyvoice.utils.executor import Executor
ModuleNotFoundError: No module named 'cosyvoice'
```

**Comment by kexul** [comment]
> 运行训练后报错了
> 
> ```
> Traceback (most recent call last):
>   File "cosyvoice/bin/train.py", line 33, in <module>
>     from cosyvoice.utils.executor import Executor
> ModuleNotFoundError: No module named 'cosyvoice'
> ```

You may run `. path.sh` first.

**Comment by kexul** [comment]
I'll update the script to add path env in the script.

**Comment by kexul** [comment]
> 运行训练后报错了
> 
> ```
> Traceback (most recent call last):
>   File "cosyvoice/bin/train.py", line 33, in <module>
>     from cosyvoice.utils.executor import Executor
> ModuleNotFoundError: No module named 'cosyvoice'
> ```

I've updated the script, you can pull the changes and retry.

**Comment by cpken** [comment]
不行，问题依旧，还多了两个问题
```
TypeError: __init__() got an unexpected keyword argument 'precision'

TypeError: launch() got an unexpected keyword argument 'enable_queue'
```

**Comment by kexul** [comment]
> 不行，问题依旧，还多了两个问题
> 
> ```
> TypeError: __init__() got an unexpected keyword argument 'precision'
> 
> TypeError: launch() got an unexpected keyword argument 'enable_queue'
> ```

Sorry, I'm using gradio 3.50.2, you can delete these keyword...

**Comment by cpken** [comment]
现在有新的错误了，
```
Traceback (most recent call last):
  File "cosyvoice/bin/train.py", line 136, in <module>
    main()
  File "/conda_env/CosyVoice/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "cosyvoice/bin/train.py", line 90, in main
    with open(args.config, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'conf/cosyvoice.yaml'
```

**Comment by kexul** [comment]
> 现在又有新的错误了，我是不是应该要把文件的相对路径改成绝对路径？
> 
> ```
> Traceback (most recent call last):
>   File "cosyvoice/bin/train.py", line 136, in <module>
>     main()
>   File "/conda_env/CosyVoice/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>   File "cosyvoice/bin/train.py", line 90, in main
>     with open(args.config, 'r') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'conf/cosyvoice.yaml'
> ```

If you are in `examples/libritts/cosyvoice` now, there should be 'conf/cosyvoice.yaml'... That's quite weird...

**Comment by cpken** [comment]
问题没有解决，放弃使用，使用其它方式去完成训练。

**Comment by aluminumbox** [comment]
this pr is closed because we want user to train the model using shell script instead of webui, because webui training may leads to lots of environment problem which is hard to debug

**Comment by DreamingEric** [comment]
> 问题没有解决，放弃使用，使用其它方式去完成训练。

请问有什么方式去训练自己的音色呢？找了很久都没找到，谢谢了

**Pull request closed without merging**
