### PR TITLE
Support MPS Backend

### PR DESCRIPTION
**Pull request by XXXXRT666**
Add MPS support; now you can use –device to select MPS, CUDA, or CPU.

### CODE REVIEW

**Comment by aluminumbox** [comment]
can we detect mps in code rather than specify device argument, then we can change only one file model.py line 22.

**Comment by XXXXRT666** [comment]
Yes, I kept the default setting just because I haven't tested whether it's faster or not on a larger vram machine. On my M2 chip Mac I suppose it's may slower than CPU (No exact timing)

**Comment by XXXXRT666** [comment]
I will test it later on a machine with larger vram

**Comment by aluminumbox** [comment]
> Yes, I kept the default setting just because I haven't tested whether it's faster or not on a larger vram machine. On my M2 chip Mac I suppose it's may slower than CPU (No exact timing)

hello, please add me in Dingding group. My name is 铝箱.  Please add me to discuss further details.

**Comment by XXXXRT666** [comment]
> hello, please add me in Dingding group. My name is 铝箱. Please add me to discuss further details.

I have enter the DingTalk group, but I think private messaging is not allowed.

> Yes, I kept the default setting just because I haven't tested whether it's faster or not on a larger vram machine. On my M2 chip Mac I suppose it's may slower than CPU (No exact timing)

And for MPS inference, it takes 100s in average for default text in webUI, while it only takes 37s in average for CPU. Also MPS have unsolved memory leaks issue, the memory increases by 8 GB after inferencing a sentence. So I set it a second choice, the default device is CUDA for Nvidia GPU and CPU for others.

**Comment by aluminumbox** [comment]
> > hello, please add me in Dingding group. My name is 铝箱. Please add me to discuss further details.
> 
> I have enter the DingTalk group, but I think private messaging is not allowed.
> 
> > Yes, I kept the default setting just because I haven't tested whether it's faster or not on a larger vram machine. On my M2 chip Mac I suppose it's may slower than CPU (No exact timing)
> 
> And for MPS inference, it takes 100s in average for default text in webUI, while it only takes 37s in average for CPU. Also MPS have unsolved memory leaks issue, the memory increases by 8 GB after inferencing a sentence. So I set it a second choice, the default device is CUDA for Nvidia GPU and CPU for others.

@XXXXRT666 please add me now, I have removed the restriction.

**Pull request closed without merging**
